Fix invalid bufnr  errors
steelsojka/completion-buffers pull request #5
Opened 2020-07-11 13:47 UTC by rickysaurav

* Fix the call to get the current bufnr

2020-07-11 21:32 UTC, steelsojka requested changes

2020-07-11 21:32 UTC, steelsojka commented on lua/completion_buffers/source.lua
> +  return M.get_completion_items(vim.tbl_keys(M.get_words(vim.fn.bufnr())), prefix, "Buffer")
what may be a better solution is using the nvim api. `vim.api.nvim_get_current_buf()` instead of `vim.fn.bufnr('.')` This will return the correct bufnr

2020-07-12 15:22 UTC, rickysaurav commented on lua/completion_buffers/source.lua
> +  return M.get_completion_items(vim.tbl_keys(M.get_words(vim.fn.bufnr())), prefix, "Buffer")
Changed

2020-07-13 10:40 UTC, sanga commented
:+1: I just came here to report this bug. Nice to find that the fix is already in the works! Cheers

2020-07-13 11:38 UTC, steelsojka approved these changes

2020-07-13 11:38 UTC, merged